// react/components/application-ui/layout/dividers/with_label.jsx
/* This example requires Tailwind CSS v2.0+ */
export default function Example() {
  return (
    <div className="relative">
      <div className="absolute inset-0 flex items-center" aria-hidden="true">
        <div className="w-full border-t border-gray-300" />
      </div>
      <div className="relative flex justify-center">
        <span className="px-2 bg-white text-sm text-gray-500">Continue</span>
      </div>
    </div>
  )
}

// vue/components/application-ui/layout/dividers/with_label.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <div class="relative">
    <div class="absolute inset-0 flex items-center" aria-hidden="true">
      <div class="w-full border-t border-gray-300" />
    </div>
    <div class="relative flex justify-center">
      <span class="px-2 bg-white text-sm text-gray-500"> Continue </span>
    </div>
  </div>
</template>
