// vue/components/application-ui/layout/panels/well__edge_to_edge_on_mobile.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <!-- Be sure to use this with a layout container that is full-width on mobile -->
  <div class="bg-gray-50 overflow-hidden sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <!-- Content goes here -->
    </div>
  </div>
</template>

// react/components/application-ui/layout/panels/well__edge_to_edge_on_mobile.jsx
/* This example requires Tailwind CSS v2.0+ */
export default function Example() {
  return (
    <>
      {/* Be sure to use this with a layout container that is full-width on mobile */}
      <div className="bg-gray-50 overflow-hidden sm:rounded-lg">
        <div className="px-4 py-5 sm:p-6">{/* Content goes here */}</div>
      </div>
    </>
  )
}
