// react/components/application-ui/layout/containers/narrow_constrained_with_padded_content.jsx
/* This example requires Tailwind CSS v2.0+ */
export default function Example() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      {/* We've used 3xl here, but feel free to try other max-widths based on your needs */}
      <div className="max-w-3xl mx-auto">{/* Content goes here */}</div>
    </div>
  )
}

// vue/components/application-ui/layout/containers/narrow_constrained_with_padded_content.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <!-- We've used 3xl here, but feel free to try other max-widths based on your needs -->
    <div class="max-w-3xl mx-auto">
      <!-- Content goes here -->
    </div>
  </div>
</template>
